In [49]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 608.4/608.4 kB 5.6 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

WARNING: Ignoring invalid distribution ~orch (D:\anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (D:\anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (D:\anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (D:\anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (D:\anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (D:\anaconda\Lib\site-packages)

In [2]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
import emoji

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mithl\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [3]:
dep = pd.read_csv('Suicide Sentiment Data\\Negative_Neutral_Depression\\Depression.csv')

In [4]:
dep

      Label                                               TEXT Unnamed: 2
0         1  I was once a kind romantic who strove to help ...        NaN
1         1  ! I wake up every day thinking why am I living...        NaN
2         1  I have problems with my girlfriend. I cannot b...        NaN
3         1  My whole life is one continuous hell, in which...        NaN
4         1  I want to sleep and not wake up. Every day the...        NaN
...     ...                                                ...        ...
4572      1  I have lost everything ... there is no homelan...        NaN
4573      1  It is very hard mentally. On the eve of the Ne...        NaN
4574      1  At first, the people around me, in the person ...        NaN
4575      1  , I really need help, otherwise I feel that I ...        NaN
4576      1  Do not want to live. I was doing well before. ...        NaN

[4577 rows x 3 columns]

In [5]:
dep.describe(include='all')

         Label       TEXT Unnamed: 2
count   4577.0       4573          1
unique     NaN       4307          1
top        NaN  Good day.          s
freq       NaN          5          1
mean       1.0        NaN        NaN
std        0.0        NaN        NaN
min        1.0        NaN        NaN
25%        1.0        NaN        NaN
50%        1.0        NaN        NaN
75%        1.0        NaN        NaN
max        1.0        NaN        NaN

In [6]:
dep["Unnamed: 2"].value_counts()

Unnamed: 2
s    1
Name: count, dtype: int64

In [7]:
txt = (dep[dep["Unnamed: 2"] == 's']['TEXT']+dep[dep["Unnamed: 2"] == 's']['Unnamed: 2'])
txt.values

<ArrowStringArray>
['Fell in love with a girl to the point of exhaustion. For a long time I could not admit, as in life I was shy and modest, prone to depression. Because of this, I could never communicate with girls + they all disgusted me, because now it is in fashion to drink, smoke, swear, etc. And she is not that, she is smart, beautiful, well-mannered, I did not believe that there are such wonderful girls in our rotten time. Then, when we walked home from school, talked, when we were alone, I confessed that I liked her. She smiled sweetly and averted her eyes - she was shy, reciprocated, we hugged and walked by the hand, and then for the first time I felt what happiness is. Then why am I writing to this suicide site, you ask? Her father found out that she "got a boy", met me at school, told me not to approach her anymore, since I was not worthy of her, and she only needed to think about studying (I am from a dysfunctional family + I have even I have no friends + I study at 4, sometimes 3, but she only at 5). I told him that we only communicate platonically, that he may be overly worried, but I don’t understand why, without even giving me a chance, answered: “She has nothing to communicate with people like you. Do you understand me?”. Now she avoids me, doesn't even say , just glances, so do I. Sadness runs through my chest and I want to commit suicide.s']
Length: 1, dtype: str

In [8]:
dep["TEXT"] = dep["TEXT"].add(dep["Unnamed: 2"], fill_value='')

In [9]:
dep[dep["TEXT"].isnull()]

      Label TEXT Unnamed: 2
345       1  NaN        NaN
2400      1  NaN        NaN
2651      1  NaN        NaN
2976      1  NaN        NaN

In [10]:
dep["Label"].value_counts() == len(dep)

Label
1    True
Name: count, dtype: bool

Now, we can safely drop the duplicates as the labels are always 1 for all text in this dataframe and The null values of TEXT are not helpful in our textual analysis part too.

*Removal of Missing Values*

In [11]:
dep.dropna(subset=["TEXT"],inplace=True)

In [12]:
dep

      Label                                               TEXT Unnamed: 2
0         1  I was once a kind romantic who strove to help ...        NaN
1         1  ! I wake up every day thinking why am I living...        NaN
2         1  I have problems with my girlfriend. I cannot b...        NaN
3         1  My whole life is one continuous hell, in which...        NaN
4         1  I want to sleep and not wake up. Every day the...        NaN
...     ...                                                ...        ...
4572      1  I have lost everything ... there is no homelan...        NaN
4573      1  It is very hard mentally. On the eve of the Ne...        NaN
4574      1  At first, the people around me, in the person ...        NaN
4575      1  , I really need help, otherwise I feel that I ...        NaN
4576      1  Do not want to live. I was doing well before. ...        NaN

[4573 rows x 3 columns]

*Text Cleaning*

In [13]:
def cleaningText(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r"'", "", text)
    text = re.sub(r'\W+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [14]:
dep["TEXT"] = dep["TEXT"].apply(cleaningText)

In [15]:
dep

      Label                                               TEXT Unnamed: 2
0         1  i was once a kind romantic who strove to help ...        NaN
1         1  i wake up every day thinking why am i living m...        NaN
2         1  i have problems with my girlfriend i cannot be...        NaN
3         1  my whole life is one continuous hell in which ...        NaN
4         1  i want to sleep and not wake up every day the ...        NaN
...     ...                                                ...        ...
4572      1  i have lost everything there is no homeland ch...        NaN
4573      1  it is very hard mentally on the eve of the new...        NaN
4574      1  at first the people around me in the person of...        NaN
4575      1  i really need help otherwise i feel that i wil...        NaN
4576      1  do not want to live i was doing well before sh...        NaN

[4573 rows x 3 columns]

*Tokenization*

In [17]:
def tokenizeText(text):
    return word_tokenize(text)

In [18]:
list(word_tokenize(dep.iloc[0]["TEXT"]))

['i',
 'was',
 'once',
 'a',
 'kind',
 'romantic',
 'who',
 'strove',
 'to',
 'help',
 'anyone',
 'who',
 'asked',
 'i',
 'never',
 'felt',
 'sorry',
 'for',
 'myself',
 'i',
 'believed',
 'in',
 'humanity',
 'however',
 'all',
 'this',
 'was',
 'fake',
 'surrogate',
 'friendship',
 'and',
 'some',
 'kind',
 'of',
 'incomprehensible',
 'relationship',
 'the',
 'girl',
 'who',
 'swore',
 'that',
 'she',
 'loved',
 'eventually',
 'cheated',
 'and',
 'went',
 'to',
 'another',
 'another',
 'did',
 'not',
 'appear',
 'i',
 'am',
 'hopeless',
 'but',
 'simply',
 'without',
 'sufficient',
 'income',
 'and',
 'my',
 'own',
 'housing',
 'parents',
 'with',
 'schizophrenia',
 'f',
 'i',
 'have',
 'never',
 'been',
 'supported',
 'or',
 'supported',
 'by',
 'anyone',
 'so',
 'giving',
 'a',
 'piece',
 'of',
 'myself',
 'to',
 'everyone',
 'i',
 'have',
 'already',
 'lost',
 'my',
 'spiritual',
 'warmth',
 'i',
 'became',
 'indifferent',
 'apathy',
 'the',
 'ex',
 'girlfriend',
 'effortlessly',
 'found',
 'a',
 'new',
 'one',
 'who',
 'immediately',
 'married',
 'her',
 'and',
 'takes',
 'her',
 'to',
 'different',
 'countries',
 'of',
 'the',
 'world',
 'of',
 'course',
 'i',
 'took',
 'on',
 'any',
 'job',
 'to',
 'show',
 'that',
 'it',
 'was',
 'not',
 'worse',
 'but',
 'i',
 'was',
 'often',
 'deceived',
 'underpaid',
 'or',
 'not',
 'paid',
 'at',
 'all',
 'i',
 'am',
 'a',
 'simple',
 'loser',
 'who',
 'has',
 'lost',
 'the',
 'meaning',
 'of',
 'life',
 'even',
 'my',
 'appearance',
 'does',
 'not',
 'save',
 'my',
 'situation',
 'it',
 'is',
 'terrible',
 'just',
 'a',
 'freak',
 'therefore',
 'i',
 'often',
 'envy',
 'those',
 'who',
 'are',
 'lucky',
 'with',
 'their',
 'appearance',
 'how',
 'they',
 'are',
 'loved',
 'and',
 'how',
 'everything',
 'is',
 'easy',
 'for',
 'them',
 'i',
 'do',
 'my',
 'favorite',
 'thing',
 'but',
 'i',
 'often',
 'think',
 'that',
 'no',
 'one',
 'needs',
 'it',
 'just',
 'like',
 'me',
 'all',
 'this',
 'is',
 'in',
 'vain',
 'meaningless',
 'it',
 'affects',
 'the',
 'emptiness',
 'inside',
 'me',
 'it',
 'is',
 'often',
 'surprising',
 'how',
 'lucky',
 'many',
 'people',
 'are',
 'how',
 'they',
 'have',
 'it',
 'all',
 'and',
 'why',
 'nothing',
 'works',
 'out',
 'for',
 'me',
 'why',
 'everything',
 'turns',
 'out',
 'somehow',
 'wrong',
 'either',
 'they',
 'will',
 'lose',
 'my',
 'documents',
 'or',
 'they',
 'will',
 'not',
 'pay',
 'me',
 'exactly',
 'then',
 'it',
 'is',
 'my',
 'place',
 'that',
 'will',
 'be',
 'closed',
 'it',
 'is',
 'me',
 'used',
 'and',
 'abandoned',
 'i',
 'have',
 'such',
 'parents',
 'sometimes',
 'i',
 'want',
 'everyone',
 'around',
 'me',
 'to',
 'be',
 'in',
 'my',
 'place',
 'to',
 'feel',
 'all',
 'this',
 'for',
 'themselves',
 'and',
 'understand',
 'what',
 'it',
 'is',
 'like',
 'but',
 'even',
 'deeper',
 'i',
 'just',
 'want',
 'to',
 'stop',
 'it',
 'all',
 'just',
 'interrupt',
 'my',
 'existence']

In [19]:
dep["TEXT"] = dep["TEXT"].apply(tokenizeText)

In [20]:
dep.iloc[1].values

array([np.int64(1),
       list(['i', 'wake', 'up', 'every', 'day', 'thinking', 'why', 'am', 'i', 'living', 'my', 'life', 'is', 'empty', 'and', 'meaningless', 'i', 'have', 'neither', 'a', 'husband', 'nor', 'children', 'nor', 'even', 'a', 'relationship', 'some', 'kind', 'of', 'hopeless', 'total', 'loneliness', 'that', 'does', 'not', 'end', 'in', 'any', 'way', 'all', 'my', 'attempts', 'to', 'get', 'to', 'know', 'someone', 'do', 'not', 'end', 'in', 'anything', 'i', 'try', 'to', 'do', 'something', 'but', 'nothing', 'comes', 'of', 'it', 'i', 'flounder', 'floundering', 'but', 'things', 'are', 'not', 'moving', 'forward', 'i', 'understand', 'and', 'realize', 'that', 'this', 'is', 'how', 'it', 'will', 'be', 'and', 'the', 'older', 'i', 'get', 'the', 'worse', 'and', 'do', 'not', 'say', 'how', 'to', 'occupy', 'yourself', 'distract', 'yourself', 'tried', 'does', 'not', 'help', 'because', 'of', 'all', 'these', 'experiences', 'my', 'health', 'has', 'fallen', 'i', 'sleep', 'badly', 'i', 'practically', 'do', 'not', 'eat', 'anything', 'maybe', 'it', 's', 'better', 'i', 'will', 'slowly', 'die', 'further', 'existence', 'is', 'meaningless', 'im', 'just', 'taking', 'someone', 'elses', 'place']),
       nan], dtype=object)

The data analysis part will be taken part to check if we should remove the stop words and eventually carry on to the stemming and lemmatization

In [21]:
dep.to_csv("depressionCleanedDataset.csv")

***suicidalTendencyData***

In [24]:
df = pd.read_csv('Suicide Sentiment Data\\Negative_Neutral_Depression\\Suicadal_tendencies_data.csv', encoding = 'latin1')

In [25]:
df

      Label                                               TEXT
0         2               I don't know what to do with my life
1         2                              I think it's tonight.
2         2                                Day 1: Realizations
3         2  I'm writing a story were somebody is talked ou...
4         2                                Idk. Help. I guess.
...     ...                                                ...
7061      2  To (you, my love)I'm sorry about the things I'...
7062      2  My girlfriend has recently started cutting hea...
7063      2  I had an NDE in 2009 after an ATV accident and...
7064      2                              Just simply, Why not?
7065      2  And I have no life or friends to celebrate wit...

[7066 rows x 2 columns]

In [26]:
df.describe(include='all')

         Label                   TEXT
count   7066.0                   7061
unique     NaN                   5680
top        NaN  I want to kill myself
freq       NaN                      3
mean       2.0                    NaN
std        0.0                    NaN
min        2.0                    NaN
25%        2.0                    NaN
50%        2.0                    NaN
75%        2.0                    NaN
max        2.0                    NaN

In [27]:
df[df["TEXT"].isnull()]

      Label TEXT
4794      2  NaN
5459      2  NaN
5755      2  NaN
6662      2  NaN
6779      2  NaN

In [28]:
df["Label"].value_counts() == len(df)

Label
2    True
Name: count, dtype: bool

*Removal of Missing Values and Cleaning Text*

In [29]:
df.dropna(subset=["TEXT"],inplace=True)

In [ ]:
df["TEXT"].value_counts()

In [31]:
def cleaningText(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r"'", "", text)
    text = re.sub(r'\W+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return word_tokenize(text)

In [32]:
df["TEXT"] = df["TEXT"].apply(cleaningText)

In [33]:
df

      Label                                               TEXT
0         2      [i, dont, know, what, to, do, with, my, life]
1         2                           [i, think, its, tonight]
2         2                                [day, realizations]
3         2  [im, writing, a, story, were, somebody, is, ta...
4         2                              [idk, help, i, guess]
...     ...                                                ...
7061      2  [to, you, my, love, im, sorry, about, the, thi...
7062      2  [my, girlfriend, has, recently, started, cutti...
7063      2  [i, had, an, nde, in, after, an, atv, accident...
7064      2                           [just, simply, why, not]
7065      2  [and, i, have, no, life, or, friends, to, cele...

[7061 rows x 2 columns]

The data analysis part will be taken part to check if we should remove the stop words and eventually carry on to the stemming and lemmatization

In [35]:
df.to_csv("suicidalTendenciesDataCleaned.csv")

***neutralTendencyData***

In [36]:
neutral = pd.read_csv('Suicide Sentiment Data\\Negative_Neutral_Depression\\Neutral.csv', encoding='latin1')

In [37]:
neutral

      Label                                               TEXT
0       0.0  TIL the movie Starship Troopers was never adap...
1       0.0                       What do you call a fat baby?
2       0.0  Two morons are sitting on a fence. The big one...
3       0.0                  I covered all my weapons in glue.
4       0.0  Joke I made up: Caveman and a bear walk into a...
...     ...                                                ...
6069    NaN   Perfect. Thank you. Enjoy your sunday of no work
6070    NaN   haha. It does have a nice ring to it (: Lets ...
6071    NaN                                  Hahah. Love them!
6072    NaN   jass warn me b4 u go to nxt war...i am there ...
6073    NaN  going to work soon and so excited!  ugh id rat...

[6074 rows x 2 columns]

In [38]:
neutral.describe(include='all')

         Label    TEXT
count   1893.0    6065
unique     NaN    6059
top        NaN  #NAME?
freq       NaN       3
mean       0.0     NaN
std        0.0     NaN
min        0.0     NaN
25%        0.0     NaN
50%        0.0     NaN
75%        0.0     NaN
max        0.0     NaN

In [39]:
neutral.isnull().sum()

Label    4181
TEXT        9
dtype: int64

In [40]:
neutral["Label"].value_counts() == len(neutral)

Label
0.0    False
Name: count, dtype: bool

Now, we can safely drop the duplicates as the labels are always 1 for all text in this dataframe and The null values of TEXT are not helpful in our textual analysis part too.

*Removal of Missing Values Values and Cleaning Text*

In [41]:
neutral.dropna(subset=["TEXT"],inplace=True)

In [42]:
neutral

      Label                                               TEXT
0       0.0  TIL the movie Starship Troopers was never adap...
1       0.0                       What do you call a fat baby?
2       0.0  Two morons are sitting on a fence. The big one...
3       0.0                  I covered all my weapons in glue.
4       0.0  Joke I made up: Caveman and a bear walk into a...
...     ...                                                ...
6069    NaN   Perfect. Thank you. Enjoy your sunday of no work
6070    NaN   haha. It does have a nice ring to it (: Lets ...
6071    NaN                                  Hahah. Love them!
6072    NaN   jass warn me b4 u go to nxt war...i am there ...
6073    NaN  going to work soon and so excited!  ugh id rat...

[6065 rows x 2 columns]

In [43]:
def cleaningText(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r"'", "", text)
    text = re.sub(r'\W+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return word_tokenize(text)

In [44]:
neutral["TEXT"] = neutral["TEXT"].apply(cleaningText)

In [45]:
neutral

      Label                                               TEXT
0       0.0  [til, the, movie, starship, troopers, was, nev...
1       0.0                [what, do, you, call, a, fat, baby]
2       0.0  [two, morons, are, sitting, on, a, fence, the,...
3       0.0           [i, covered, all, my, weapons, in, glue]
4       0.0  [joke, i, made, up, caveman, and, a, bear, wal...
...     ...                                                ...
6069    NaN  [perfect, thank, you, enjoy, your, sunday, of,...
6070    NaN  [haha, it, does, have, a, nice, ring, to, it, ...
6071    NaN                                [hahah, love, them]
6072    NaN  [jass, warn, me, b, u, go, to, nxt, war, i, am...
6073    NaN  [going, to, work, soon, and, so, excited, ugh,...

[6065 rows x 2 columns]

In [46]:
neutral.iloc[0].values

array([np.float64(0.0),
       list(['til', 'the', 'movie', 'starship', 'troopers', 'was', 'never', 'adapted', 'into', 'a', 'successful', 'video', 'game', 'because'])],
      dtype=object)

The data analysis part will be taken part to check if we should remove the stop words and eventually carry on to the stemming and lemmatization

In [47]:
neutral.to_csv("neutralDataCleanedDataset.csv")